#pragma config(Motor,  motorA,          right,         tmotorNXT, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorB,          left,          tmotorNXT, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          steer,         tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
motor[motorA, 100]
motor[motorB,100]
}
